//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partie", Namespace="http://schemas.datacontract.org/2004/07/Refac.Data")]
    [System.SerializableAttribute()]
    public partial class Partie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotADevinerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbCoupsRestantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatternEnCoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotADeviner {
            get {
                return this.MotADevinerField;
            }
            set {
                if ((object.ReferenceEquals(this.MotADevinerField, value) != true)) {
                    this.MotADevinerField = value;
                    this.RaisePropertyChanged("MotADeviner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbCoupsRestants {
            get {
                return this.NbCoupsRestantsField;
            }
            set {
                if ((this.NbCoupsRestantsField.Equals(value) != true)) {
                    this.NbCoupsRestantsField = value;
                    this.RaisePropertyChanged("NbCoupsRestants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatternEnCours {
            get {
                return this.PatternEnCoursField;
            }
            set {
                if ((object.ReferenceEquals(this.PatternEnCoursField, value) != true)) {
                    this.PatternEnCoursField = value;
                    this.RaisePropertyChanged("PatternEnCours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultat {
            get {
                return this.ResultatField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultatField, value) != true)) {
                    this.ResultatField = value;
                    this.RaisePropertyChanged("Resultat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPartiePendu")]
    public interface IPartiePendu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartiePendu/VerifierLettre", ReplyAction="http://tempuri.org/IPartiePendu/VerifierLettreResponse")]
        Client1.ServiceReference1.Partie VerifierLettre(Client1.ServiceReference1.Partie p, string lettre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartiePendu/VerifierLettre", ReplyAction="http://tempuri.org/IPartiePendu/VerifierLettreResponse")]
        System.Threading.Tasks.Task<Client1.ServiceReference1.Partie> VerifierLettreAsync(Client1.ServiceReference1.Partie p, string lettre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartiePenduChannel : Client1.ServiceReference1.IPartiePendu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartiePenduClient : System.ServiceModel.ClientBase<Client1.ServiceReference1.IPartiePendu>, Client1.ServiceReference1.IPartiePendu {
        
        public PartiePenduClient() {
        }
        
        public PartiePenduClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartiePenduClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartiePenduClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartiePenduClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client1.ServiceReference1.Partie VerifierLettre(Client1.ServiceReference1.Partie p, string lettre) {
            return base.Channel.VerifierLettre(p, lettre);
        }
        
        public System.Threading.Tasks.Task<Client1.ServiceReference1.Partie> VerifierLettreAsync(Client1.ServiceReference1.Partie p, string lettre) {
            return base.Channel.VerifierLettreAsync(p, lettre);
        }
    }
}
