//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneDeCommande
    {
        public int IdLigneDeCommande { get; set; }
        public int Quantite { get; set; }
        public int FkPromotion { get; set; }
        public int FkLivre { get; set; }
        public int FkCommande { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Livre Livre { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
