//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabseFirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLanguage
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string Langage { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
