//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabseFirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class table2
    {
        public int Id { get; set; }
        public string VaLueT2 { get; set; }
        public Nullable<int> IdTable1 { get; set; }
        public Nullable<int> IdTable3 { get; set; }
    
        public virtual table1 table1 { get; set; }
        public virtual table3 table3 { get; set; }
    }
}
