//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenteBouquin_DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VenteBouquinContext : DbContext
    {
        public VenteBouquinContext()
            : base("name=VenteBouquinContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<LigneDeCommande> LigneDeCommandes { get; set; }
        public virtual DbSet<Livre> Livres { get; set; }
        public virtual DbSet<LivreCategory> LivreCategories { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
